- README.md
- fern/asyncapi-overrides.yml
- sets overrides for async listen api
- updates readme to explain how to access the API Playground locally
- adds helpful comments to this config for future reference
BEFORE
AFTER
---
- https://app.asana.com/0/0/1209427878411272
> updates overrides for async listen api

- fern/docs/redaction.mdx
- fern/snippets/specific-languages-only.mdx
- pre-recorded output  and streaming redacted output is now the same.
- no_delay=true will cause issues with redaction when streaming.
- Redaction should be documented as a string, not boolean.
-  See related Spec PR: https://github.com/deepgram/internal-api-specs/pull/79
- Live streaming redaction now works with nova models and smart formatting no need for a call out.
- Adds a specific language only component for language options.
---
- https://app.asana.com/0/0/1207533846839506
- https://app.asana.com/0/0/1208563324126249
> update redaction for new streaming behavior

- fern/fern.config.json
This CLI version resolves the `Enum value 16000 is not suitable for code generation` error raised during `fern check`.
> Bump CLI version.

- fern/docs/sdk-feature-matrix.mdx
- Removes no delay from pre-recorded as that isn't a feature of pre-recorded
- Removes the websocket  message table as we no longer document these as SDK Features.
> updates matrix for no delay

- fern/docs.yml
- We've opted to disable this feature as the repo is going to be made private.
-  the feature is commented out, in case we want to use it again the future.
---
- https://app.asana.com/0/0/1209505051506237
> disables edit-this-page

- fern/docs.yml
this redirect was causing issues with routes that contained `/documentation` only. in the case of the Marketing site using `https://developers.deepgram.com/documentation/` to point to our Docs site.
now all routes  that use`/documentation` will go to `/home`and this will load our docs home page
---
- https://app.asana.com/0/0/1209576954582841
> chore: fixes incorrect redirect

- fern/docs.yml
> chore: fixes incorrect redirect for tts-chunking article

- fern/docs/maintaining.mdx
One of my new links for the STT models page was incorrect in the self-hosted maintenance page. This corrects that error.
> Corrected 'new' link for STT models page

- fern/generators.yml
Sets the setting `shouldGenerateWebsocketClients = true`, which enables automated websocket client code generation.
> chore(cli): Update ts generator config.

- fern/docs/smart-format.mdx
Updating smart format docs to reflect formatting timeout of 3s, and some updates to no_delay section as well.
> Update smart-format.mdx - formatting timeout and no_delay

- fern/asyncapi-overrides.yml
- fern/docs.yml
- fern/fern.config.json
- fern/generators.yml
This PR includes updates that:
1. Combine the `textToSpeech` and `speak` clients in the generated SDKs.
2. Overrides individual types in AsyncAPI specs.
3. Enable forward compatible enums in generated SDKs.
> chore: Updates for SDK generation & overrides.

- fern/docs/streaming-text-to-speech.mdx
Found the issue when using this code sample locally - probably just forgot to rename the local variable when copy/pasting from the STT example?
> Fix typo in streaming tts docs

- fern/docs.yml
- fern/docs/improving-aura-2-formatting.mdx
Left the url paths to prevent breaking changes.
> Make the doc name clearer for the end user

- fern/docs/api-rate-limits.mdx
Changes include: renaming 'Aura' to 'Aura-1', pointing to the TTS REST and Streaming 'Getting Started' pages for all Aura-1 and Aura-2 links, adding warning messages about Aura-2 streaming not being supported, setting the rate limit for REST Aura-2 to 5 for PayGo/Growth and Enterprise.
> Updated rate limits for Aura-2. 

- fern/docs/authentication.mdx
- Clarifies call out and where short lived tokens can be used in terms of which APIs support them.
> chore:improves callout

- fern/docs/text-to-speech-prompting.mdx
- fern/docs/text-to-speech.mdx
- fern/docs/tts-bit-rate.mdx
- fern/docs/tts-container.mdx
Context: https://deepgram.slack.com/archives/C066Y86ENQJ/p1745595132044839
People are being confused by what seems like high response times - what they see is the time-to-last-byte. Let's call that out in our cURL commands.
TODO: this notably doesn't touch anything related to our SDKs, so customers won't get any signals about TTFB vs TTLB when using the SDK.
> Always output ttfb for tts samples

- fern/docs/models-languages-overview.mdx
Answered a question on this today and realized it was a bit hard to find, so IMO better to note in models/lang overview page as well. Whoever reviews this -- I was also debating calling this out 'even with multi-lingual models' but decided this was cleaner.
> Update models-languages-overview.mdx with default language=en note

- fern/assets/component.js
- fern/assets/styles.css
- fern/docs/landing.mdx
This PR implements necessary changes to prepare Deepgram's docs for Fern's frontend upgrade. 
Improvements include:
- improved color scales (grayscale and accent color scales are adjusted to more closely match the provided colors)
- more consistent styles across all markdown pages: content body is thinner for better reading experience, and border - radiuses around cards all adjusted to be uniform.
- spacing and border radius can now be adjusted using the --spacing and --radius css variables. You can now shrink the radius or make spacing around content tighter or wider to match your branding.
- better in-browser performance (less client-side javascript, and less HTML)
- bug-fixes for search—including support for mobile view
- improved sidebar (state is saved between tab navigation), and …
> [WIP] 🌿: prepare new frontend changes

- fern/docs/drivers-and-containerization-platforms.mdx
The minimum version is now 12.4 with no upper limit as of May 19th, 2025.
> Updated CUDA Version information for self-hosted.

- fern/docs/configure-voice-agent.mdx
- fern/docs/voice-agent-settings.mdx
- updates Docs for context length 
- relates to https://github.com/deepgram/internal-api-specs/pull/112
---
- https://app.asana.com/0/0/1210403316564378
> Adds context_length content

- fern/pages/guides/fundamentals/token-based-authentication.mdx
Small copy change to reflect that this is now supported
> Reflect that agent supports token-based auth

- fern/docs/configure-voice-agent.mdx
This is indicated as lowercase in the spec. `max`, not `Max`.
> fix: correct casing for context length "max" value

- fern/docs/voice-agent-tts-models.mdx
- link was pointing to cartesia docs
- example used a 11labs flash model
- used a call out to make it more clear of our support of turbo 2.5 only
> fixed 11labs link

- fern/docs/configure-voice-agent.mdx
- relates to https://github.com/orgs/deepgram/discussions/1278 
- multi language is currently disallowed with Deepgram TTS but works with 11 labs only
> removes mention of multi support

- fern/docs/voice-agent-llm-models.mdx
Update voice agent LLM models documentation to reflect current pricing tiers and availability:
- Change table headers from "Availability" to "Pricing Tier" for clarity
- Update OpenAI models:
- gpt-4.1: Advanced (temporarily available in Standard)
- gpt-4.1-mini: Standard
- gpt-4.1-nano: Standard
- gpt-4o: Advanced (temporarily available in Standard)
- gpt-4o-mini: Standard (changed from GA)
- Update Anthropic models:
- claude-3-5-haiku-latest: Standard
- claude-sonnet-4-20250514: Advanced (temporarily available in Standard)
- Remove claude-3-haiku-20240307 (no longer available)
- Add clear indication for Advanced tier models that are temporarily available in Standard tier
- Maintain Google models as "Coming Soon!" status
This update provides users with accurate information about current …
> update LLM model availability and pricing tiers
