fern/docs/self-hosted-self-service-tutorial.mdx
fern/docs/tts-encoding.mdx

- fixes curl command issue with tts encoding.
- fixes what's next header
---
- https://app.asana.com/0/0/1209480570134965
- https://app.asana.com/0/0/1209480568904185

fixes issues found during migration

---

fern/docs.yml
fern/docs/code-of-conduct.mdx
fern/docs/support.mdx
fern/fern.config.json
fern/hidden-pages/code-of-conduct.mdx

- some prettier lint
- adds code of conduct page
-  links new page to Support page
- bumps Fern CLI
---
- https://app.asana.com/0/0/1209505051506241

adds code of conduct

---

fern/docs.yml

- now with the ISC license in place, we've re-enables edit this page and made the repo public

chore: re-enables edit this page

---

fern/docs/maintaining.mdx
fern/docs/using-sdks-with-self-hosted.mdx

Updated a handful of doc pages in anticipation of the Nova-3 self-hosted launch.

Nova 3 updates

---

fern/docs/api-rate-limits.mdx

adds info call out about upcoming rate limit changes for STT: Batch & Streaming

adds info call out

---

fern/docs/voice-agent.mdx

adds link to gh repo to VA demo list

adds link to new demo

---

fern/docs/keyterm.mdx

- adds samples on using multiple keyterms with deliminters of `20%` and `+`
---
- https://app.asana.com/0/0/1209801527832149

chore: adds samples on using multiple keyterms

---

fern/docs/the-deepgram-model-improvement-partnership-program.mdx

a request from Jason R. to remove this as it's redundant information. Confirmed with @natalierutgers 
---
- https://app.asana.com/0/0/1209829339396555

chore: removes extra verbiage

---

fern/docs.yml
fern/docs/authentication.mdx
fern/openapi-overrides.yml

- Adds a proper section to docs.yml for the new ephemeral Auth API
- Adds a info call out to Authorization page 
- some linting on fern-override file 
---
- https://app.asana.com/0/0/1209675638387588

adds authorization section to docs.yml

---

fern/docs/multilingual-code-switching.mdx

- updates callout to point to model list for multilingual support
---
- https://app.asana.com/0/0/1209866584931919

chore: updates callout to point to model list

---

fern/hidden-pages/aura-2-preview.mdx

1. Updated column headers:
- Changed `english format` to `language` in all voice tables for better clarity
2. Voice Removals:
- Removed Cressida voice entries from both "All Available Voices" and "Accented English Voices" tables
- Total voice count is now 41 voices
- Featured English (US) voices
- All Available Voices
- Accented English Voices

Updates to the Aura-2 docs to improve voice listings and formatting.

---

fern/docs/voice-agent-settings-configuration.mdx

this should have been removed yesterday

removes ref to aura-2 model

---

fern/docs/voice-agent-starter-apps.mdx

Adds the new node voice agent stater to apps.

chore:adds node VA starter

---

fern/docs/summarization.mdx

including info to answer [this customer question](https://deepgram.slack.com/archives/C07K5MKDTRQ/p1743760312199929) around minimum word threshold for summarization.

Update summarization.mdx with minimum word threshold (>50 words for summarization)

---

fern/docs/keyterm.mdx

Capitalization expectations/behavior/recs added to keyterm docs. related thread -- https://deepgram.slack.com/archives/C07HJD6P21X/p1744998967889919

Update keyterm.mdx w capitalization info

---

fern/docs/text-summarization.mdx

Also updated code sample to not mislead with an input token count of 50 or fewer (although tokens != words)

Update text-summarization.mdx with summarization minimum words

---

fern/docs/keyterm.mdx

chore: typo correction

---

fern/docs/encoding.mdx

I discussed these changes with @ajsyp on Slack before opening this PR.

Added `linear32`,`alaw`, and `ogg-opus` while also correcting the description for `opus`

---

fern/docs/language.mdx

Had another customer question here, and I couldn't find the answer answer in docs so I had to verify myself. 
NOTE(!!!) -- I would like at least one person who knows about this to confirm that this is true (and if there are any caveats across other languages), if any reviewer can that's great, if not we should confirm with team.

Update language.mdx with specified language behavior

---

fern/assets/styles.css

Reducing header font size and padding to save vertical space
---
- https://app.asana.com/0/0/1210062211779669

Reducing font size and padding on header 

---

fern/docs.yml
fern/docs/voice-agent-update-prompt.mdx

- adds update prompt to docs as it was missed in the v1 release
---
- https://app.asana.com/0/0/1210191160180743
- https://app.asana.com/0/0/1210191160182994

fix: adds update prompt

---

fern/docs/voice-agent-starter-apps.mdx

- adds new starter for flask
- sets column to 3

chore:adds flask starter

---

fern/docs/dotnet-sdk-streaming-text-to-speech.mdx
fern/docs/go-sdk-streaming-text-to-speech.mdx
fern/docs/improving-aura-2-formatting.mdx
fern/docs/js-sdk-streaming-text-to-speech.mdx
fern/docs/python-sdk-streaming-text-to-speech.mdx
fern/docs/send-llm-outputs-to-the-tts-web-socket.mdx
fern/docs/streaming-text-to-speech.mdx

updates all TTS WS related content for aura-2 support

chore:updates ws content for aura-2

---

fern/docs/voice-agent-v1-migration.mdx

This migration guide was written with the steps I had to undergo to upgrade the Gnosis API from Early Access to the V1 version of the Voice Agent API, I found this order and structure of a migration guide very helpful, and more reflective of how I wrote the SDK migration guides

feat: Update voice-agent-v1-migration.mdx

---

fern/docs/build-a-function-call.mdx

Updates guide to align with code changes from https://github.com/deepgram-devs/flask-agent-function-calling-demo/pull/12
---
- https://app.asana.com/0/0/1210164296685265

Updated Build a Function Call Guide

---

fern/docs/configure-voice-agent.mdx
fern/docs/voice-agent-settings.mdx
fern/docs/voice-agent-tts-models.mdx

- adds Polly Docs
- ensure all fields are properly represented for `speak` 
-  adds proper examples for each 3rd party provider for ease of understanding
---
- https://app.asana.com/0/0/1210345354414361

feat: updates docs for Polly

---

fern/docs/streaming-text-to-speech.mdx

chore: tts per min fix

---

fern/docs/api-rate-limits.mdx

- updates rates for support of aura-2 streaming
-  removes un-necessary warning message at bottom of rate tables.
- updates aura-1 streaming rates
---
- https://app.asana.com/0/0/1210394062559215

updates for aura-2 streaming

---

fern/docs/voice-agent-llm-models.mdx

- adds supported open ai models for clarity in Docs
---
- https://app.asana.com/0/0/1210407293351214

adds open_ai models

---

fern/asyncapi-overrides.yml
fern/pages/guides/deep-dives/the-deepgram-model-improvement-partnership-program.mdx

- Adds addition MIPs content
- Adds code samples for all APIs and SDK Languages
- Adds Fern async overrides for incoming API Spec change: https://github.com/deepgram/internal-api-specs/pull/115 
**Note: these are commented out right now so Fern Builds correctly** 
> We'll want to merge in the API Spec change first, then remove the comments so the API Explorer gets the proper overrides applied. 
---
- https://app.asana.com/0/0/1210441305753559

[WIP] TTS Docs Improvements

---

fern/pages/home.mdx

this link to GH was incorrect.

fixes bad link for js sdk

---

fern/docs/voice-agent-tts-models.mdx

Fixes Cartesia provider examples 
References Used:
*  https://docs.cartesia.ai/2025-04-16/api-reference/tts/tts
* https://elevenlabs.io/docs/api-reference/text-to-speech/v-1-text-to-speech-voice-id-stream-input
---
- https://app.asana.com/0/0/1210417771101156

[WIP] Corrects TTS provider examples

---

fern/docs/configure-voice-agent.mdx

- Clarify language selection based on use case (specific vs multi)
- Add important note about model-language compatibility
- Improve link formatting for supported languages

Improve agent.language configuration guidance

---

fern/assets/styles.css

The left nav needs a little breathing room on the left and it's not aligned with the top menu. Adding some padding so the left it's aligned. 
Before: 
After:

Adding left padding to the menu on the left

---

fern/docs/voice-agent.mdx
fern/generators.yml

- included fixes from #252 to fix incorrect agent options
- Bumps Fern Generators

chore/fix Agent docs + bump generators

---

fern/docs.yml
fern/docs/voice-agent-inject-user-message.mdx

- adds docs for inject user message 
- adds nav item for inject user
Relates to: https://github.com/deepgram/internal-api-specs/pull/118/
---
- https://app.asana.com/0/0/1210489778526220

Feat: adds inject user docs

---

fern/docs.yml
fern/docs/introduction.mdx
fern/docs/tts-models.mdx
fern/pages/home.mdx

Reorganizes the TTS models documentation to improve user experience and future-proof for additional languages.
Key Changes
Page title: "Voice Selection" → "Voices and Languages"
Language support: Added comprehensive section with current/future language roadmap
Navigation: Organized voices by language with clear featured sections
Spanish voices: Highlighted featured voices (Celeste, Estrella, Nestor) and codeswitching capabilities
Future-proofing: Scalable structure for easy addition of new languages
Impact
Easier voice discovery by language
Clear highlighting of versatile voices
Better information about codeswitching capabilities
Improved structure for future language additions

Restructure TTS Voice Selection docs: Add language support section and improve navigation
